import type { TourGuideStep } from '@/types'

export const tourGuideSteps: TourGuideStep[] = [
  {
    id: 'intro',
    stage: '说明',
    title: 'rpy-tool 项目说明',
    body: '本项目全程本地处理，强烈建议先用 Git 等版本管理纳入项目再使用，主要服务于脚本编写完成后的校对、审阅、修改与立绘差分，未来计划支持全流程工作流。',
    view: 'home',
    anchor: 'app-brand',
  },
  {
    id: 'open-workspace',
    stage: '启动',
    title: '打开 RenPy 工作区',
    body: '点这里选择项目目录，建议选中包含脚本与资源的 game 目录（或项目根目录）。',
    view: 'home',
    anchor: 'workspace-action',
  },
  {
    id: 'asset-rules',
    stage: '资产',
    title: '资产索引逻辑',
    body: '资产页按路径规则把 图片 / 音频 归类为 角色、CG、背景、BGM 等，并标出未被引用的资源。点顶部「路径规则」按钮，从工作区目录可视化生成 glob 规则。',
    view: 'assets',
    anchor: 'asset-rules',
    requiresWorkspace: true,
  },
  {
    id: 'sprite-apply',
    stage: '立绘',
    title: '快速更换已有角色的立绘差分',
    body: '选中一条对白行，右侧会列出该角色的所有立绘状态，点击即可直接改写对白头部（如 e happy "..."）。',
    view: 'sprite',
    anchor: 'sprite-inspector',
    requiresWorkspace: true,
  },
  {
    id: 'review-pass',
    stage: '校对',
    title: '文本 Review',
    body: '选择行来进行校对操作，用 1 / 2 / 3 / 0 快捷键标记，可写备注、修改意见和导入导出校对结果。',
    view: 'review',
    anchor: 'review-inspector',
    requiresWorkspace: true,
  },
  {
    id: 'visual-edit',
    stage: '编辑',
    title: '可视化编辑器',
    body: '结构化编辑，主要用于校对过程中的零散补改。需要直接改源码时，用编辑区顶部的「源文件 (Monaco)」切换即可打开 Monaco 编辑原始 .rpy。',
    view: 'visual',
    anchor: 'visual-mode-switch',
    requiresWorkspace: true,
  },
  {
    id: 'about-guide',
    stage: '关于',
    title: '随时回到这套引导',
    body: '关于页放主题、过渡动画等设置；想再看一遍这套引导，可以从这里或顶栏「引导」按钮重新打开。',
    view: 'about',
    anchor: 'about-guide-actions',
    requiresWorkspace: true,
  },
]
